sudo: required
language: node_js
node_js:
  - 10

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.4

script:
  - docker-compose -f docker-compose.prod.yml up -d --build

deploy:
  provider: script
  script: bash ./deploy_heroku.sh
