sudo: required
language: node_js
node_js:
  - 10
services:
  - docker
addons:
  ssh_known_hosts:
    - $VPS_HOST
env:
  - DOCKER_COMPOSE_VERSION=1.25.4
script:
  - docker-compose -f docker-compose.prod.yml up -d --build
after_success:
  - bash ./deploy.sh
