sudo: required
language: node_js
node_js:
  - 10

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.4

script:
  - docker-compose -f docker-compose.prod.yml up -d --build

deploy:
  provider: script
  script: bash ./deploy.sh
  #    wget -qO- https://toolbelt.heroku.com/install.sh | sh
  #    docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
  #    docker tag reminderapi:latest registry.heroku.com/reminderapi/web
  #    docker push registry.heroku.com/reminderapi/web
  on:
    branch: master, dev
