sudo: required
language: node_js
node_js:
  - 10
services:
  - docker
addons:
  ssh_known_hosts:
    - 68.183.73.58
env:
  - DOCKER_COMPOSE_VERSION=1.25.4
script:
  - echo "build app"
after_success:
  - openssl aes-256-cbc -K $encrypted_79dc1e55e56d_key -iv $encrypted_79dc1e55e56d_iv
    -in deploy_rsa_key.enc -out deploy_rsa_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa_key
  - ssh-add deploy_rsa_key
  - ssh deploy@68.183.73.58 "echo 'success connected' && exit"
