language: node_js
node_js:
  - 10

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.25.4

script:
  - docker-compose -f docker-compose.prod.yml up -d --build

after_success:
  - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - heroku container:login
  - heroku container:push web
#  - sudo docker tag reminderapi:latest registry.heroku.com/reminderapi/web
#  - sudo docker push registry.heroku.com/reminderapi/web
