sudo: required
language: node_js
node_js:
  - 10
services:
  - docker
addons:
  ssh_known_hosts:
    - 68.183.73.58
env:
  - DOCKER_COMPOSE_VERSION=1.25.4
script:
  - docker-compose up -f docker-compose.prod.yml --build -d
after_success:
  - bash ./deploy.sh
