app:
  image: rysrenat/reminder-api_server:last
  environment:
    POSTGRES_HOST: $POSTGRES_HOST
    POSTGRES_PORT: $POSTGRES_PORT
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_DB: $POSTGRES_DB
    SERVER_PORT: $SERVER_PORT

  postgres:
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      SERVER_PORT: $SERVER_PORT
