version: '3'

services:
  app:
    depends_on:
      - postgres
    ports:
      - '9000:3000'

  postgres:
    image: postgres:10.4-alpine
    ports:
      - '5432:5432'
    postgres:
      volumes:
        - dbdata:/data/db

volumes:
  dbdata:
