version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    command: npm run start:prod

  postgres:
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
