version: '3'

services:
  app:
    depends_on:
      - postgres
    networks:
      - app-network
    ports:
      - '9000:3000'

  postgres:
    image: postgres:10.4-alpine
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
