version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file: .env.local
    ports:
      - '3000:3000'
    volumes:
      - .:/app/
      - /app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres:10.4-alpine
    ports:
      - '5432:5432'
    env_file: .env.local
