version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules
    env_file: .env
    command: npm run start:dev

  postgres:
    env_file: .env
