version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      SERVER_PORT: $SERVER_PORT
    command: npm run start:prod

  postgres:
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      SERVER_PORT: $SERVER_PORT
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
